version: '3.8'
services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: leads
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"